### ISSUE TITLE
Test Suite breaking!

### ISSUE THREAD

**Issue by Talha345** [charpeni/react-native-url-polyfill#461]
Using `import {URL} from 'react-native-url-polyfill';` breaks Jest Test suite with the error  `TypeError: Cannot read properties of undefined (reading 'Version')`

```
Stack Trace:
 at Object.<anonymous> (node_modules/react-native-url-polyfill/js/ios10Fix.js:2:54)
 at Object.<anonymous> (node_modules/react-native-url-polyfill/index.js:9:1)
```

**Comment by Talha345** [comment]
Was happening because of loading the module in test suite before mocking.
