### ISSUE TITLE
Unexpected error: "The id argument must be of type string. Received undefined"

### ISSUE THREAD

**Issue by ochoav** [charpeni/react-native-url-polyfill#470]
I am trying to use this package, but I am getting an error when bundling with Expo!

Here are 2 different ways the error shows up:
```
[Error: TransformError node_modules/react-native-url-polyfill/index.js: The "id" argument must be of type string. Received undefined]
TypeError: The "id" argument must be of type string. Received undefined
    at validateString (node:internal/validators:162:11)
    at Module.require (node:internal/modules/cjs/loader:1228:3)
    at require (node:internal/modules/helpers:176:18)
    at transformJS (apps/mobile/node_modules/metro-transform-worker/src/index.js:230:35)
    at transformJSWithBabel (apps/mobile/node_modules/metro-transform-worker/src/index.js:372:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.transform (apps/mobile/node_modules/metro-transform-worker/src/index.js:518:12)
```

```
error: node_modules/react-native-url-polyfill/index.js: The "id" argument must be of type string. Received undefined
```

I'm not sure what to make of this! I wonder if it's related to an incompatible metro package alongside the rest of our setup? 

Lmk if I can provide more info!

**Comment by charpeni** [comment]
Thanks for reporting this. The report predates substantial implementation and packaging changes in `v3` and `v4`.

Could you try `react-native-url-polyfill@4.0.0`? If this is still happening, please reopen the issue with a minimal reproduction and the Expo SDK, React Native, Metro, and Node versions, plus the import statement being transformed. That will let us determine whether this is a Metro configuration or package-resolution problem.
